
SRCS = ujprog.c
CFLAGS += -Wall
FTLIB = `libftdi1-config  --libs` `libftdi1-config  --cflags`
USBLIB = -lusb-1.0

# Install libusb and libftdi with 'brew install libusb libftdi'

ujprog:	${SRCS}
	${CC} ${CFLAGS} ${SRCS} ${FTLIB} ${USBLIB} -o ujprog

flash:	ft232r_flash.c
	${CC} ${CFLAGS} -lusb ft232r_flash.c ${FTLIB} -o ft232r_flash

install: ujprog
	install -m 4755 ujprog /usr/local/bin

clean:
	rm -f ujprog ujprog.o *~

depend:
	mkdep ${INCLUDES} ${SRCS}
