
SRCS = ujprog.c
CFLAGS += -Wall -D__linux__
#FTLIB = /usr/lib/`uname -m`-linux-gnu/libftdi.a
FTLIB = -lftdi

ujprog:	${SRCS}
	${CC} ${CFLAGS} -lusb ${SRCS} ${FTLIB} -o ujprog

flash:	ft232r_flash.c
	${CC} ${CFLAGS} -lusb ft232r_flash.c ${FTLIB} -o ft232r_flash
	
install: ujprog
	install -m 4755 ujprog /usr/local/bin

clean:
	rm -f ujprog ujprog.o

depend:
	mkdep ${INCLUDES} ${SRCS}
